font:
  size: 7.0

  # normal: 
  #   family: Hasklig
  #   style: Regular

  # bold:
  #   family: Hasklig
  #   style: Bold

  # italic:
  #   family: Hasklig
  #   style: Italic


schemes:
  solarized_light: &light
    primary:
      background: '#fdf6e3' # base3
      foreground: '#657b83' # base00

    cursor:
      text:   '#fdf6e3' # base3
      cursor: '#657b83' # base00

    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3

  gruvbox_dark: &gruvbox_dark
    # Default colors
    primary:
      # hard contrast: background = '#1d2021'
      background: '#282828'
      # soft contrast: background = '#32302f'
      foreground: '#ebdbb2'

    # Normal colors
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

  theme_dark: &dark
    # Default colors
    primary:
      background: '#1c1c1c'
      foreground: '#d2d4de'

    # Normal colors
    normal:
      black:   '#161821'
      red:     '#e27878'
      green:   '#b4be82'
      yellow:  '#e2a478'
      blue:    '#84a0c6'
      magenta: '#a093c7'
      cyan:    '#89b8c2'
      white:   '#c6c8d1'

    # Bright colors
    bright:
      black:   '#6b7089'
      red:     '#e98989'
      green:   '#c0ca8e'
      yellow:  '#e9b189'
      blue:    '#91acd1'
      magenta: '#ada0d3'
      cyan:    '#95c4ce'
      white:   '#d2d4de'


    nord: &nord
      primary:
        background: '#2E3440'
        foreground: '#D8DEE9'

      # Normal colors
      normal:
        black:   '#3B4252'
        red:     '#BF616A'
        green:   '#A3BE8C'
        yellow:  '#EBCB8B'
        blue:    '#81A1C1'
        magenta: '#B48EAD'
        cyan:    '#88C0D0'
        white:   '#E5E9F0'

      # Bright colors
      bright:
        black:   '#4C566A'
        red:     '#BF616A'
        green:   '#A3BE8C'
        yellow:  '#EBCB8B'
        blue:    '#81A1C1'
        magenta: '#B48EAD'
        cyan:    '#8FBCBB'
        white:   '#ECEFF4'

colors: *gruvbox_dark

key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance           }
  - { key: K,        mods: Control, action: ScrollPageUp,   mode: ~Alt       }
  - { key: J,        mods: Control, action: ScrollPageDown, mode: ~Alt       }
