#! /usr/bin/env perl

my $blanked = 0;
open (IN, "xscreensaver-command -watch |");
while (<IN>) {
    if (m/^(BLANK)/) {
        if (!$blanked) {
            $blanked = 1;
            system "pactl set-sink-mute \@DEFAULT_SINK\@ 1";
            system "systemctl suspend";
        }
    } elsif (m/^UNBLANK/) {
        $blanked = 0;
    }
}
