#!/bin/sh

while read file 
do
  case "$1" in
  "r")
    convert -rotate 90 -- "${file}" "${file}" ;;
  "R")
    convert -rotate -90 -- "${file}" "${file}" ;;
  "y")
    readlink -f -- "${file}" | xclip -selection clipboard ;;
  "d")
    rm -- "${file}" ;;
  "t")
    telegram-desktop -sendpath "$(readlink -f -- "${file}")" 1>/dev/null 2>&1;;
  esac
done
