#!/bin/sh

while read file 
do
  case "$1" in
  "r")
    convert -rotate 90 "$file" "$file" ;;
  "R")
    convert -rotate -90 "$file" "$file" ;;
  "y")
    echo -n "$file" | xclip -selection clipboard ;;
  "d")
    rm -- "$file" ;;
  esac
done
